language: node_js
node_js:
  - "node"
  - "4"
addons:
  firefox: "latest"
  apt:
    packages:
      - oracle-java8-set-default
install: npm install
before_install:
  - if [[ `npm -v` = 2* ]]; then npm i -g npm@3; fi
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./node_modules/.bin/webdriver-manager update
  - ./node_modules/.bin/webdriver-manager start &
  - sleep 3
