language: node_js
node_js:
  - "node"
install: npm install
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sh -e ./node_modules/.bin/webdriver-manager update
- sh -e ./node_modules/.bin/webdriver-manager start &
- sleep 3
