addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "node"
before_install: 
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
install: npm install
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- ./node_modules/protractor/bin/install_selenium_standalone
- java -jar selenium/selenium-server-standalone-2.35.0.jar -Dwebdriver.chrome.driver=./selenium/chromedriver &
- sleep 3
